// Auto-generated from study plan data
// 16-week AI Engineer study plan — 112 tasks, 331 resource links

// ══════════════════════════════════════════════════════════════
//  PLAN DATA
// ══════════════════════════════════════════════════════════════
export const PHASES = [
  {
    id: 1, label: 'Phase 1',
    title: 'ML/DL Foundations & LLM Internals',
    subtitle: 'Deeply understand how transformers, LLMs, and embeddings work — not just use them.',
    weeks: [
      { week: 1, days: [
        { d:'Mon', t:'Read: "Attention Is All You Need" (arxiv 1706.03762). Implement multi-head self-attention from scratch in PyTorch — no high-level libraries.',
          r:[{t:'Attention Is All You Need',u:'https://arxiv.org/abs/1706.03762'},{t:'The Illustrated Transformer',u:'https://jalammar.github.io/illustrated-transformer/'},{t:'PyTorch Docs',u:'https://pytorch.org/docs/stable/index.html'}]},
        { d:'Tue', t:'Study positional encoding, layer norm, residual connections. Read: The Annotated Transformer.',
          r:[{t:'The Annotated Transformer',u:'https://nlp.seas.harvard.edu/annotated-transformer/'},{t:'Layer Norm Paper',u:'https://arxiv.org/abs/1607.06450'}]},
        { d:'Wed', t:'Study pre-training objectives: MLM (BERT), CLM (GPT), T5 prefix-LM. Understand why each matters for different downstream tasks.',
          r:[{t:'BERT Paper',u:'https://arxiv.org/abs/1810.04805'},{t:'GPT-2 Paper',u:'https://cdn.openai.com/better-language-models/language_models_are_unsupervised_multitask_learners.pdf'},{t:'T5 Paper',u:'https://arxiv.org/abs/1910.10683'}]},
        { d:'Thu', t:'Dive into RLHF: read InstructGPT paper. Understand reward modeling, PPO, and DPO as a simpler alternative.',
          r:[{t:'InstructGPT Paper',u:'https://arxiv.org/abs/2203.02155'},{t:'DPO Paper',u:'https://arxiv.org/abs/2305.18290'},{t:'HuggingFace RLHF Blog',u:'https://huggingface.co/blog/rlhf'}]},
        { d:'Fri', t:'Study tokenization: BPE, WordPiece, SentencePiece. Implement a simple BPE tokenizer from scratch. Understand token economics.',
          r:[{t:'BPE Paper',u:'https://arxiv.org/abs/1508.07909'},{t:'HuggingFace Tokenizers',u:'https://huggingface.co/docs/tokenizers/index'},{t:'Tiktokenizer (interactive)',u:'https://tiktokenizer.vercel.app/'}]},
        { d:'Sat', t:'Study embeddings deeply: cosine similarity, dot-product, L2 distance. Implement semantic search from scratch with NumPy only.',
          r:[{t:'Understanding Embeddings (Simon Willison)',u:'https://simonwillison.net/2023/Oct/23/embeddings/'},{t:'Word2Vec Paper',u:'https://arxiv.org/abs/1301.3781'},{t:'NumPy Docs',u:'https://numpy.org/doc/stable/'}]},
        { d:'Sun', t:"Build a mini GPT following Karpathy's nanoGPT. Run it on a small dataset and understand each component.",
          r:[{t:'nanoGPT (GitHub)',u:'https://github.com/karpathy/nanoGPT'},{t:"Karpathy: Let's build GPT (video)",u:'https://www.youtube.com/watch?v=kCc8FmEb1nY'}]},
      ]},
      { week: 2, days: [
        { d:'Mon', t:'Study fine-tuning paradigms: full fine-tune, LoRA, QLoRA, prefix-tuning, prompt-tuning. Understand parameter efficiency tradeoffs.',
          r:[{t:'LoRA Paper',u:'https://arxiv.org/abs/2106.09685'},{t:'QLoRA Paper',u:'https://arxiv.org/abs/2305.14314'},{t:'HuggingFace PEFT Docs',u:'https://huggingface.co/docs/peft/index'}]},
        { d:'Tue', t:'Hands-on: fine-tune a small model (e.g. Llama 3.1 8B) with LoRA using HuggingFace PEFT on a domain-specific dataset.',
          r:[{t:'TRL SFT Trainer',u:'https://huggingface.co/docs/trl/sft_trainer'},{t:'Llama models on HuggingFace',u:'https://huggingface.co/meta-llama'},{t:'PEFT Docs',u:'https://huggingface.co/docs/peft/index'}]},
        { d:'Wed', t:'Study evaluation metrics: BLEU, ROUGE, BERTScore, perplexity. When each is appropriate and why they all have limitations.',
          r:[{t:'BERTScore Paper',u:'https://arxiv.org/abs/1904.09675'},{t:'ROUGE Paper',u:'https://aclanthology.org/W04-1013/'},{t:'HuggingFace Evaluate',u:'https://huggingface.co/docs/evaluate/index'}]},
        { d:'Thu', t:'Study loss functions: cross-entropy, contrastive loss, triplet loss. Understand how embedding models are trained (SimCSE, E5, BGE).',
          r:[{t:'SimCSE Paper',u:'https://arxiv.org/abs/2104.08821'},{t:'E5 Embeddings Paper',u:'https://arxiv.org/abs/2212.03533'},{t:'BGE on HuggingFace',u:'https://huggingface.co/BAAI/bge-large-en-v1.5'}]},
        { d:'Fri', t:'Read Scaling Laws for Neural LMs and Chinchilla. Understand compute-optimal training.',
          r:[{t:'Scaling Laws Paper',u:'https://arxiv.org/abs/2001.08361'},{t:'Chinchilla Paper',u:'https://arxiv.org/abs/2203.15556'}]},
        { d:'Sat', t:'Study mixture of experts (MoE): Mixtral architecture. Understand routing, expert capacity, and load balancing.',
          r:[{t:'Mixtral Paper',u:'https://arxiv.org/abs/2401.04088'},{t:'Switch Transformer',u:'https://arxiv.org/abs/2101.03961'},{t:'MoE Explainer (HuggingFace)',u:'https://huggingface.co/blog/moe'}]},
        { d:'Sun', t:"Review week. Write a 1-page 'tech note' explaining LLM internals to a non-ML engineer (practice for the mentorship expectation).",
          r:[{t:'Julian.com Writing Guide',u:'https://www.julian.com/guide/write/intro'},{t:'Google Technical Writing Course',u:'https://developers.google.com/tech-writing'}]},
      ]},
    ]
  },
  {
    id: 2, label: 'Phase 2',
    title: 'RAG, Vector Databases & Agent Frameworks',
    subtitle: 'Master modern RAG pipelines and leading agent frameworks, going beyond vanilla approaches.',
    weeks: [
      { week: 3, days: [
        { d:'Mon', t:'Study RAG architecture end-to-end: chunking strategies, embedding, indexing, retrieval, reranking, generation. Draw the full pipeline.',
          r:[{t:'RAG Paper (Lewis et al.)',u:'https://arxiv.org/abs/2005.11401'},{t:'Pinecone RAG Guide',u:'https://www.pinecone.io/learn/retrieval-augmented-generation/'},{t:'LangChain RAG Concepts',u:'https://python.langchain.com/docs/concepts/rag/'}]},
        { d:'Tue', t:'Hands-on: build a RAG pipeline with LlamaIndex over a technical doc corpus. Use FAISS as the vector store.',
          r:[{t:'LlamaIndex Starter Example',u:'https://docs.llamaindex.ai/en/stable/getting_started/starter_example/'},{t:'FAISS Docs',u:'https://faiss.ai/'},{t:'LlamaIndex Docs',u:'https://docs.llamaindex.ai'}]},
        { d:'Wed', t:'Study chunking deeply: fixed-size, sentence, semantic, hierarchical. Implement and compare retrieval quality across strategies.',
          r:[{t:'Chunking Strategies Guide (Pinecone)',u:'https://www.pinecone.io/learn/chunking-strategies/'},{t:'LlamaIndex Node Parsers',u:'https://docs.llamaindex.ai/en/stable/module_guides/loading/node_parsers/'},{t:'Semantic Chunking Paper',u:'https://arxiv.org/abs/2312.06648'}]},
        { d:'Thu', t:'Study reranking: cross-encoder vs bi-encoder, Cohere Rerank, BGE reranker. Add reranking to your pipeline and measure improvement.',
          r:[{t:'Cohere Rerank Docs',u:'https://docs.cohere.com/docs/reranking'},{t:'BGE Reranker (HuggingFace)',u:'https://huggingface.co/BAAI/bge-reranker-large'},{t:'SBERT Cross-Encoders',u:'https://www.sbert.net/examples/applications/cross-encoder/README.html'}]},
        { d:'Fri', t:'Study advanced retrieval: HyDE, RAG-Fusion, multi-query retrieval, self-query retrievers. Implement at least one.',
          r:[{t:'HyDE Paper',u:'https://arxiv.org/abs/2212.10496'},{t:'RAG-Fusion Paper',u:'https://arxiv.org/abs/2402.03367'},{t:'LangChain Multi-Query Retriever',u:'https://python.langchain.com/docs/how_to/MultiQueryRetriever/'}]},
        { d:'Sat', t:'Build the same RAG app with LangChain. Compare framework tradeoffs: LlamaIndex vs LangChain for retrieval use cases.',
          r:[{t:'LangChain RAG Tutorial',u:'https://python.langchain.com/docs/tutorials/rag/'},{t:'LangChain Docs',u:'https://python.langchain.com/docs/'},{t:'LlamaIndex vs LangChain',u:'https://www.datacamp.com/blog/langchain-vs-llamaindex'}]},
        { d:'Sun', t:'Study vector databases: FAISS, Chroma, Pinecone, Weaviate, pgvector. Benchmark query latency/recall tradeoffs at different scales.',
          r:[{t:'Chroma Docs',u:'https://docs.trychroma.com/'},{t:'Weaviate Docs',u:'https://weaviate.io/developers/weaviate'},{t:'pgvector (GitHub)',u:'https://github.com/pgvector/pgvector'},{t:'ANN Benchmarks',u:'https://ann-benchmarks.com/'}]},
      ]},
      { week: 4, days: [
        { d:'Mon', t:'Study where RAG breaks: out-of-distribution queries, context window limits, hallucination in generation. Document failure modes systematically.',
          r:[{t:'10 Ways to Improve RAG (Databricks)',u:'https://www.databricks.com/blog/10-ways-to-improve-the-performance-of-retrieval-augmented-generation-systems'},{t:'RAGAS Eval Framework',u:'https://docs.ragas.io'}]},
        { d:'Tue', t:'Study when NOT to use RAG: fine-tuning vs RAG decision framework. Read "RAG vs Fine-tuning" (arxiv 2401.08406).',
          r:[{t:'RAG vs Fine-tuning Paper',u:'https://arxiv.org/abs/2401.08406'},{t:'Fine-tuning vs RAG (Anyscale)',u:'https://www.anyscale.com/blog/fine-tuning-vs-retrieval-what-is-the-best-source-of-truth-for-your-llm'},{t:'OpenAI Fine-tuning Guide',u:'https://platform.openai.com/docs/guides/fine-tuning'}]},
        { d:'Wed', t:'Hands-on: LangChain agents with tool use. Build an agent that can query a SQL DB, call an API, and do web search in a single turn.',
          r:[{t:'LangChain Agent Executor',u:'https://python.langchain.com/docs/how_to/agent_executor/'},{t:'LangChain Tool Calling',u:'https://python.langchain.com/docs/how_to/tool_calling/'},{t:'LangChain Built-in Tools',u:'https://python.langchain.com/docs/integrations/tools/'}]},
        { d:'Thu', t:'Explore LlamaIndex Workflows and Semantic Kernel. Understand how each models agent state, tool calling, and orchestration.',
          r:[{t:'LlamaIndex Workflows',u:'https://docs.llamaindex.ai/en/stable/understanding/workflows/'},{t:'Semantic Kernel Docs',u:'https://learn.microsoft.com/en-us/semantic-kernel/overview/'},{t:'Semantic Kernel (GitHub)',u:'https://github.com/microsoft/semantic-kernel'}]},
        { d:'Fri', t:'Study structured outputs: JSON mode, function calling, tool schemas. Build an agent using OpenAI function calling + Pydantic.',
          r:[{t:'OpenAI Function Calling',u:'https://platform.openai.com/docs/guides/function-calling'},{t:'OpenAI Structured Outputs',u:'https://platform.openai.com/docs/guides/structured-outputs'},{t:'Pydantic Docs',u:'https://docs.pydantic.dev/'}]},
        { d:'Sat', t:'Read: ReAct (arxiv 2210.03629), Toolformer (arxiv 2302.04761), Self-Ask (arxiv 2210.06726). Understand reasoning-action loops.',
          r:[{t:'ReAct Paper',u:'https://arxiv.org/abs/2210.03629'},{t:'Toolformer Paper',u:'https://arxiv.org/abs/2302.04761'},{t:'Self-Ask Paper',u:'https://arxiv.org/abs/2210.06726'}]},
        { d:'Sun', t:'Build a "beyond RAG" demo: combine retrieval + structured reasoning + tool use in one coherent pipeline. Document design choices.',
          r:[{t:'Building Production RAG (Anyscale)',u:'https://www.anyscale.com/blog/a-comprehensive-guide-for-building-rag-based-llm-applications-part-1'},{t:'Advanced RAG Techniques',u:'https://towardsdatascience.com/advanced-retrieval-augmented-generation-from-theory-to-llamaindex-implementation-4de1464a9930'}]},
      ]},
    ]
  },
  {
    id: 3, label: 'Phase 3',
    title: 'Advanced Agentic Patterns & Multi-Agent Systems',
    subtitle: 'Design, build and reason about production-grade agentic systems with complex orchestration.',
    weeks: [
      { week: 5, days: [
        { d:'Mon', t:'Read: LLM-as-Orchestrator survey (arxiv 2309.07864). Study task decomposition patterns: sequential, parallel, conditional, loop.',
          r:[{t:'LLM Orchestrator Survey',u:'https://arxiv.org/abs/2309.07864'},{t:'Building Effective Agents (Anthropic)',u:'https://www.anthropic.com/research/building-effective-agents'},{t:'LangGraph Concepts',u:'https://langchain-ai.github.io/langgraph/concepts/'}]},
        { d:'Tue', t:'Hands-on: build a multi-step planning agent (decompose → assign sub-agents → aggregate results). Use LangGraph or LlamaIndex Workflows.',
          r:[{t:'LangGraph Tutorials',u:'https://langchain-ai.github.io/langgraph/tutorials/'},{t:'LangGraph Docs',u:'https://langchain-ai.github.io/langgraph/'},{t:'LlamaIndex Workflows',u:'https://docs.llamaindex.ai/en/stable/understanding/workflows/'}]},
        { d:'Wed', t:'Study LangGraph deeply: nodes, edges, conditional routing, state management, human-in-the-loop. Build a stateful research agent.',
          r:[{t:'LangGraph How-Tos',u:'https://langchain-ai.github.io/langgraph/how-tos/'},{t:'LangGraph Human-in-the-loop',u:'https://langchain-ai.github.io/langgraph/concepts/human_in_the_loop/'},{t:'LangGraph State Management',u:'https://langchain-ai.github.io/langgraph/concepts/low_level/'}]},
        { d:'Thu', t:'Study multi-agent frameworks: AutoGen, CrewAI, Google ADK. Understand when multi-agent adds value vs adds complexity and overhead.',
          r:[{t:'AutoGen (GitHub)',u:'https://github.com/microsoft/autogen'},{t:'CrewAI Docs',u:'https://docs.crewai.com/'},{t:'Google ADK Docs',u:'https://google.github.io/adk-docs/'}]},
        { d:'Fri', t:'Study agent memory types: short-term (conversation), episodic (summaries), semantic (vector), procedural (tool patterns). Implement a memory module.',
          r:[{t:'MemGPT Paper',u:'https://arxiv.org/abs/2310.08560'},{t:'LangGraph Memory Concepts',u:'https://langchain-ai.github.io/langgraph/concepts/memory/'},{t:'Zep (agent memory)',u:'https://www.getzep.com/'}]},
        { d:'Sat', t:'Read: Tree of Thoughts (arxiv 2305.10601), Self-Consistency (arxiv 2203.11171), Chain-of-Thought (arxiv 2201.11903). Implement ToT for a reasoning task.',
          r:[{t:'Tree of Thoughts Paper',u:'https://arxiv.org/abs/2305.10601'},{t:'Self-Consistency Paper',u:'https://arxiv.org/abs/2203.11171'},{t:'Chain-of-Thought Paper',u:'https://arxiv.org/abs/2201.11903'}]},
        { d:'Sun', t:'Study graceful degradation: circuit breakers, fallback chains, retry with backoff, deterministic fallback when LLM fails or is unavailable.',
          r:[{t:'Circuit Breaker Pattern (Fowler)',u:'https://martinfowler.com/bliki/CircuitBreaker.html'},{t:'Tenacity (Python retry)',u:'https://tenacity.readthedocs.io/'},{t:'LangChain Fallbacks',u:'https://python.langchain.com/docs/how_to/fallbacks/'}]},
      ]},
      { week: 6, days: [
        { d:'Mon', t:'Study prompt engineering systematically: zero-shot, few-shot, CoT, system prompts, persona prompting, structured output prompting.',
          r:[{t:'OpenAI Prompt Engineering Guide',u:'https://platform.openai.com/docs/guides/prompt-engineering'},{t:'Anthropic Prompt Guide',u:'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview'},{t:'PromptingGuide.ai',u:'https://www.promptingguide.ai/'}]},
        { d:'Tue', t:'Build a prompt management system: versioned prompts stored in a registry, A/B testable, with typed input/output schemas.',
          r:[{t:'LangSmith Prompt Hub',u:'https://docs.smith.langchain.com/prompt-hub'},{t:'Langfuse Prompt Management',u:'https://langfuse.com/docs/prompts/get-started'},{t:'PromptLayer',u:'https://promptlayer.com/'}]},
        { d:'Wed', t:'Study agentic patterns for data engineering: code-gen agents, pipeline-gen agents, self-healing pipelines. Design one end-to-end.',
          r:[{t:'Databricks: Data Engineering + AI',u:'https://www.databricks.com/blog/data-engineering-ai'},{t:'Apache Airflow Docs',u:'https://airflow.apache.org/docs/'},{t:'GitHub Copilot for Engineers',u:'https://docs.github.com/en/copilot'}]},
        { d:'Thu', t:'Hands-on: build a "data agent" — NL question → inspect data catalog → generate SQL → run query → explain results.',
          r:[{t:'LangChain SQL Tutorial',u:'https://python.langchain.com/docs/tutorials/sql_qa/'},{t:'Vanna.AI',u:'https://vanna.ai/'},{t:'SQLGlot (SQL parser/transpiler)',u:'https://sqlglot.com/'}]},
        { d:'Fri', t:'Study computer-use and browser-use agents. Explore Anthropic computer-use API. Understand when they are and are not appropriate.',
          r:[{t:'Anthropic Computer Use Docs',u:'https://docs.anthropic.com/en/docs/agents-and-tools/computer-use'},{t:'Browser Use (GitHub)',u:'https://github.com/browser-use/browser-use'},{t:'Playwright Python Docs',u:'https://playwright.dev/python/docs/intro'}]},
        { d:'Sat', t:'Read: Mixture of Agents (arxiv 2406.04692) and AgentBench (arxiv 2308.03688). Understand how to benchmark agentic systems.',
          r:[{t:'Mixture of Agents Paper',u:'https://arxiv.org/abs/2406.04692'},{t:'AgentBench Paper',u:'https://arxiv.org/abs/2308.03688'},{t:'GAIA Benchmark',u:'https://huggingface.co/papers/2311.12983'}]},
        { d:'Sun', t:'Write a design doc: "Architecture for a Self-Serve Analytics Agent." Include components, failure modes, cost model, and evaluation strategy.',
          r:[{t:'Design Docs at Google',u:'https://www.industrialempathy.com/posts/design-docs-at-google/'},{t:'Architecture Decision Records',u:'https://adr.github.io/'},{t:'RFC Template',u:'https://github.com/nicholasjclark/RFC-template'}]},
      ]},
    ]
  },
  {
    id: 4, label: 'Phase 4',
    title: 'Production AI: Evaluation, Guardrails & Observability',
    subtitle: 'Build eval harnesses and observability systems that actually change decisions.',
    weeks: [
      { week: 7, days: [
        { d:'Mon', t:'Study evaluation frameworks: offline evals, golden sets, LLM-as-judge, human eval, pairwise comparison. Understand tradeoffs of each.',
          r:[{t:'OpenAI Evals Framework',u:'https://github.com/openai/evals'},{t:'LLM Evaluation Guide (HuggingFace)',u:'https://huggingface.co/blog/evaluating-llms'},{t:'Promptfoo',u:'https://promptfoo.dev/'}]},
        { d:'Tue', t:'Hands-on: build an LLM-as-judge evaluator using GPT-4/Claude as judge. Include faithfulness, relevance, and coherence dimensions.',
          r:[{t:'MT-Bench / LLM-as-Judge Paper',u:'https://arxiv.org/abs/2306.05685'},{t:'G-Eval Paper',u:'https://arxiv.org/abs/2303.16634'},{t:'LangSmith Evaluation',u:'https://docs.smith.langchain.com/evaluation'}]},
        { d:'Wed', t:'Study behavioral regression testing for LLMs: how to detect when a model update breaks downstream behavior. Build a regression suite.',
          r:[{t:'Promptfoo CI/CD Testing',u:'https://promptfoo.dev/docs/ci-cd/'},{t:'LangSmith Unit Testing',u:'https://docs.smith.langchain.com/evaluation/how_to_guides/unit_testing'},{t:'Braintrust Evals',u:'https://www.braintr.us/'}]},
        { d:'Thu', t:'Study RAG-specific evals: RAGAS framework (context precision, recall, faithfulness, answer relevancy). Instrument your RAG pipeline.',
          r:[{t:'RAGAS Docs',u:'https://docs.ragas.io/'},{t:'RAGAS Paper',u:'https://arxiv.org/abs/2309.15217'},{t:'TruLens',u:'https://www.trulens.org/'}]},
        { d:'Fri', t:'Study drift monitoring for LLMs: embedding drift, output distribution shifts, topic drift. Implement a simple drift detector.',
          r:[{t:'Evidently AI Docs',u:'https://docs.evidentlyai.com/'},{t:'Arize AI',u:'https://arize.com/'},{t:'WhyLogs',u:'https://whylogs.readthedocs.io/'}]},
        { d:'Sat', t:'Study guardrails: NeMo Guardrails, Guardrails AI, LlamaGuard. Implement content safety + output schema validation for an agent.',
          r:[{t:'NeMo Guardrails (GitHub)',u:'https://github.com/NVIDIA/NeMo-Guardrails'},{t:'Guardrails AI',u:'https://www.guardrailsai.com/'},{t:'LlamaGuard Paper',u:'https://arxiv.org/abs/2312.06674'}]},
        { d:'Sun', t:'Study prompt injection, jailbreaks, indirect injection attacks. Add defenses to your data agent. Write a formal threat model.',
          r:[{t:'OWASP LLM Top 10',u:'https://owasp.org/www-project-top-10-for-large-language-model-applications/'},{t:'Prompt Injection (Simon Willison)',u:'https://simonwillison.net/2023/May/2/prompt-injection-attacks/'},{t:'Garak (LLM vuln scanner)',u:'https://github.com/leondz/garak'}]},
      ]},
      { week: 8, days: [
        { d:'Mon', t:'Study LLM observability platforms: tracing with LangSmith, Arize, Langfuse, or Helicone. Understand span tracing for multi-step agents.',
          r:[{t:'Langfuse Docs',u:'https://langfuse.com/docs'},{t:'LangSmith Docs',u:'https://docs.smith.langchain.com/'},{t:'Arize Phoenix',u:'https://phoenix.arize.com/'},{t:'Helicone',u:'https://helicone.ai/'}]},
        { d:'Tue', t:'Hands-on: instrument a LangGraph agent with full tracing — token usage, latency per step, tool call results, errors, model version.',
          r:[{t:'OpenLLMetry (OpenTelemetry for LLMs)',u:'https://github.com/traceloop/openllmetry'},{t:'LangGraph Tracing Guide',u:'https://langchain-ai.github.io/langgraph/how-tos/run-id-langsmith/'},{t:'OpenTelemetry',u:'https://opentelemetry.io/'}]},
        { d:'Wed', t:'Study structured logging for AI: what to log (inputs, outputs, latency, model, version, user context), how to make logs actionable.',
          r:[{t:'Structlog (Python)',u:'https://www.structlog.org/'},{t:'DataDog LLM Observability',u:'https://docs.datadoghq.com/llm_observability/'},{t:'ML Logging Best Practices',u:'https://neptune.ai/blog/ml-experiment-tracking'}]},
        { d:'Thu', t:'Study alerting for AI systems: when to alert on latency spikes, quality degradation, cost overruns. Build alert rules on your traced system.',
          r:[{t:'Grafana Alerting Docs',u:'https://grafana.com/docs/grafana/latest/alerting/'},{t:'Prometheus Alertmanager',u:'https://prometheus.io/docs/alerting/latest/alertmanager/'},{t:'PagerDuty API',u:'https://developer.pagerduty.com/'}]},
        { d:'Fri', t:'Study A/B testing for LLMs: traffic splitting, shadow evaluation, canary deployments for model updates. Implement a simple router.',
          r:[{t:'LangSmith A/B Testing',u:'https://docs.smith.langchain.com/evaluation/tutorials/a_b_testing'},{t:'Eppo (experimentation)',u:'https://www.geteppo.com/'},{t:'Statsig',u:'https://statsig.com/'}]},
        { d:'Sat', t:'Build an end-to-end eval pipeline: automated regression on every prompt change, LLM-as-judge scoring, dashboard with trend visualization.',
          r:[{t:'Promptfoo CI/CD',u:'https://promptfoo.dev/docs/ci-cd/'},{t:'GitHub Actions Docs',u:'https://docs.github.com/en/actions'},{t:'Langfuse Dashboards',u:'https://langfuse.com/docs/analytics/overview'}]},
        { d:'Sun', t:"Write a 'Production AI Playbook' doc: evaluation strategy, guardrails checklist, observability requirements for any new AI feature.",
          r:[{t:'Google Rules of ML',u:'https://developers.google.com/machine-learning/guides/rules-of-ml'},{t:'Made With ML: Production Guide',u:'https://madewithml.com/courses/mlops/'}]},
      ]},
    ]
  },
  {
    id: 5, label: 'Phase 5',
    title: 'Inference Optimization & LLMOps',
    subtitle: 'Master the techniques that make AI systems scale sustainably at Apple-level scale.',
    weeks: [
      { week: 9, days: [
        { d:'Mon', t:'Study quantization: INT8, INT4, GPTQ, AWQ, bitsandbytes. Benchmark quality/speed/memory tradeoffs hands-on with a local model.',
          r:[{t:'GPTQ Paper',u:'https://arxiv.org/abs/2210.17323'},{t:'AWQ Paper',u:'https://arxiv.org/abs/2306.00978'},{t:'bitsandbytes (GitHub)',u:'https://github.com/TimDettmers/bitsandbytes'},{t:'LLM.int8() Paper',u:'https://arxiv.org/abs/2208.07339'}]},
        { d:'Tue', t:'Study distillation: knowledge distillation, task-specific distillation, speculative decoding. Implement speculative decoding conceptually.',
          r:[{t:'Knowledge Distillation Paper',u:'https://arxiv.org/abs/1503.02531'},{t:'Speculative Decoding Paper',u:'https://arxiv.org/abs/2211.17192'},{t:'Assisted Generation (HuggingFace)',u:'https://huggingface.co/blog/assisted-generation'}]},
        { d:'Wed', t:'Study serving infrastructure: vLLM (PagedAttention), TGI, TensorRT-LLM, Triton. Understand throughput vs latency tradeoffs.',
          r:[{t:'vLLM Docs',u:'https://docs.vllm.ai/'},{t:'Text Generation Inference (TGI)',u:'https://huggingface.co/docs/text-generation-inference/'},{t:'TensorRT-LLM (GitHub)',u:'https://github.com/NVIDIA/TensorRT-LLM'},{t:'Triton Inference Server',u:'https://github.com/triton-inference-server/server'}]},
        { d:'Thu', t:'Hands-on: deploy a model with vLLM. Benchmark throughput at different batch sizes and concurrency levels. Plot the results.',
          r:[{t:'vLLM Quickstart',u:'https://docs.vllm.ai/en/latest/getting_started/quickstart.html'},{t:'PagedAttention Paper',u:'https://arxiv.org/abs/2309.06180'},{t:'vLLM Benchmarking Guide',u:'https://docs.vllm.ai/en/latest/performance/benchmarks.html'}]},
        { d:'Fri', t:'Study KV cache: what it is, why it matters, prefix caching. Implement cache-aware prompt design patterns.',
          r:[{t:'PagedAttention Paper (KV Cache)',u:'https://arxiv.org/abs/2309.06180'},{t:'Anthropic Prompt Caching',u:'https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching'},{t:'OpenAI Prompt Caching',u:'https://platform.openai.com/docs/guides/prompt-caching'}]},
        { d:'Sat', t:'Study batching strategies: dynamic batching, continuous batching (vLLM), request padding. Measure token throughput improvements.',
          r:[{t:'Continuous Batching (Anyscale)',u:'https://www.anyscale.com/blog/continuous-batching-llm-inference'},{t:'ORCA Paper',u:'https://www.usenix.org/conference/osdi22/presentation/yu'},{t:'vLLM Architecture Overview',u:'https://docs.vllm.ai/en/latest/design/arch_overview.html'}]},
        { d:'Sun', t:'Study token economics: cost per token, context window pricing, output vs input pricing. Build a cost estimator for an agent workflow.',
          r:[{t:'OpenAI Pricing',u:'https://openai.com/pricing'},{t:'Anthropic Pricing',u:'https://www.anthropic.com/pricing'},{t:'LLM Pricing Calculator',u:'https://huggingface.co/spaces/philschmid/llm-pricing'}]},
      ]},
      { week: 10, days: [
        { d:'Mon', t:'Study model selection frameworks: when to use GPT-4 vs Claude vs Gemini vs open models. Build a routing layer by task complexity.',
          r:[{t:'LMSYS Chatbot Arena',u:'https://chat.lmsys.org/'},{t:'Open LLM Leaderboard',u:'https://huggingface.co/spaces/open-llm-leaderboard/open_llm_leaderboard'},{t:'RouteLLM Paper',u:'https://arxiv.org/abs/2406.18665'}]},
        { d:'Tue', t:'Study MLOps: model registry, versioning, CI/CD for models (GitHub Actions → registry → deploy). Tools: MLflow, W&B, DVC. Set one up.',
          r:[{t:'MLflow Docs',u:'https://mlflow.org/docs/latest/index.html'},{t:'Weights & Biases Docs',u:'https://docs.wandb.ai/'},{t:'DVC Docs',u:'https://dvc.org/doc'}]},
        { d:'Wed', t:'Study LLMOps additions: prompt versioning, eval versioning, golden set management. Set up a simple LLMOps pipeline with MLflow.',
          r:[{t:'LLMOps (Chip Huyen)',u:'https://huyenchip.com/2023/04/11/llm-engineering.html'},{t:'MLflow LLM Tracking',u:'https://mlflow.org/docs/latest/llms/index.html'},{t:'Langfuse LLMOps',u:'https://langfuse.com/docs'}]},
        { d:'Thu', t:'Study deployment patterns: blue/green, canary, shadow mode for LLMs. Understand rollback strategies and how to implement them.',
          r:[{t:'Blue-Green Deployment (Fowler)',u:'https://martinfowler.com/bliki/BlueGreenDeployment.html'},{t:'Canary Releases (Fowler)',u:'https://martinfowler.com/bliki/CanaryRelease.html'},{t:'AWS SageMaker Deployment',u:'https://docs.aws.amazon.com/sagemaker/latest/dg/deploy-model.html'}]},
        { d:'Fri', t:'Hands-on: build a CI pipeline — push prompt change → auto-eval → if regression detected, block merge. Use GitHub Actions.',
          r:[{t:'GitHub Actions Docs',u:'https://docs.github.com/en/actions'},{t:'Promptfoo GitHub Action',u:'https://github.com/promptfoo/promptfoo-action'},{t:'LangSmith CI/CD Guide',u:'https://docs.smith.langchain.com/evaluation/tutorials/ci_cd'}]},
        { d:'Sat', t:'Study containerization for ML: Docker, multi-stage builds for model serving. Build a production-grade Dockerfile for a model server.',
          r:[{t:'Docker Docs',u:'https://docs.docker.com/'},{t:'NVIDIA Container Toolkit',u:'https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/'},{t:'vLLM Docker Guide',u:'https://docs.vllm.ai/en/latest/deployment/docker.html'}]},
        { d:'Sun', t:'Study cost optimization: semantic caching with Redis for repeated queries, batching, async queuing, right-sizing model selection.',
          r:[{t:'GPTCache (GitHub)',u:'https://github.com/zilliztech/GPTCache'},{t:'Redis Semantic Cache Blog',u:'https://redis.io/blog/llm-caching/'},{t:'Redis Docs',u:'https://redis.io/docs/'}]},
      ]},
    ]
  },
  {
    id: 6, label: 'Phase 6',
    title: 'Data Infrastructure & Natural Language Interfaces',
    subtitle: 'Build AI that sits natively on top of data infrastructure — the domain-specific differentiator.',
    weeks: [
      { week: 11, days: [
        { d:'Mon', t:'Study lakehouse architecture: Delta Lake, Apache Iceberg, Hudi. Understand ACID on data lakes, time-travel queries, schema evolution.',
          r:[{t:'Delta Lake Docs',u:'https://delta.io/'},{t:'Apache Iceberg Docs',u:'https://iceberg.apache.org/docs/latest/'},{t:'Apache Hudi Docs',u:'https://hudi.apache.org/docs/overview/'},{t:'Lakehouse Paper',u:'https://www.cidrdb.org/cidr2021/papers/cidr2021_paper17.pdf'}]},
        { d:'Tue', t:'Study distributed SQL engines: Trino/Presto architecture, query planning, cost-based optimizer, connector model. Compare with Spark SQL.',
          r:[{t:'Trino Docs',u:'https://trino.io/docs/current/'},{t:'Presto Paper (Meta)',u:'https://research.facebook.com/publications/presto-sql-on-everything/'},{t:'Trino: The Definitive Guide (free)',u:'https://trino.io/trino-the-definitive-guide.html'}]},
        { d:'Wed', t:'Hands-on: run Trino locally (Docker). Write complex analytical queries. Study and understand EXPLAIN output and query optimization.',
          r:[{t:'Trino Docker Image',u:'https://hub.docker.com/r/trinodb/trino'},{t:'Trino Getting Started',u:'https://trino.io/docs/current/installation/deployment.html'},{t:'Trino EXPLAIN Docs',u:'https://trino.io/docs/current/sql/explain.html'}]},
        { d:'Thu', t:'Study Apache Spark: DAG execution, shuffles, partitioning, catalyst optimizer. Write Spark SQL and DataFrame API for analytical workloads.',
          r:[{t:'Spark Docs',u:'https://spark.apache.org/docs/latest/'},{t:'Spark SQL Guide',u:'https://spark.apache.org/docs/latest/sql-programming-guide.html'},{t:"Learning Spark (O'Reilly)",u:'https://www.oreilly.com/library/view/learning-spark-2nd/9781492050032/'}]},
        { d:'Fri', t:'Study workflow orchestration: Apache Airflow, Prefect, Dagster. Build a DAG for a multi-step ETL pipeline with retries and observability.',
          r:[{t:'Apache Airflow Docs',u:'https://airflow.apache.org/docs/'},{t:'Prefect Docs',u:'https://docs.prefect.io/'},{t:'Dagster Docs',u:'https://docs.dagster.io/'}]},
        { d:'Sat', t:'Study streaming systems: Kafka, Apache Flink, Spark Streaming. Understand exactly-once semantics, watermarks, windowing operations.',
          r:[{t:'Kafka Documentation',u:'https://kafka.apache.org/documentation/'},{t:'Flink Docs',u:'https://nightlies.apache.org/flink/flink-docs-stable/'},{t:'Spark Structured Streaming Guide',u:'https://spark.apache.org/docs/latest/structured-streaming-programming-guide.html'}]},
        { d:'Sun', t:'Study data catalog systems: Apache Atlas, DataHub, Amundsen. Understand metadata management and how it enables AI discoverability.',
          r:[{t:'DataHub Docs',u:'https://datahubproject.io/docs/'},{t:'Amundsen Docs',u:'https://www.amundsen.io/'},{t:'Apache Atlas',u:'https://atlas.apache.org/'}]},
      ]},
      { week: 12, days: [
        { d:'Mon', t:'Study Text-to-SQL deeply: schema linking, value linking, join path reasoning. Read the Spider benchmark paper and study top systems.',
          r:[{t:'Spider Benchmark',u:'https://yale-lily.github.io/spider'},{t:'Text-to-SQL Survey',u:'https://arxiv.org/abs/2208.13629'},{t:'BIRD Benchmark',u:'https://bird-bench.github.io/'}]},
        { d:'Tue', t:'Hands-on: build a Text-to-SQL system over a real dataset (use Trino). Include schema retrieval, few-shot examples, and result validation step.',
          r:[{t:'LangChain SQL Agent',u:'https://python.langchain.com/docs/tutorials/sql_qa/'},{t:'Vanna.AI',u:'https://vanna.ai/'},{t:'DAIL-SQL Paper',u:'https://arxiv.org/abs/2308.15363'}]},
        { d:'Wed', t:'Study NL-to-SQL failure modes: ambiguous queries, wrong joins, hallucinated column names. Add a self-correction loop using query execution feedback.',
          r:[{t:'DIN-SQL Paper',u:'https://arxiv.org/abs/2304.11015'},{t:'Query Construction (LangChain Blog)',u:'https://blog.langchain.dev/query-construction/'},{t:'SQLGlot (parser/validator)',u:'https://sqlglot.com/'}]},
        { d:'Thu', t:'Build a semantic layer: map business terms → SQL patterns. Use it to improve Text-to-SQL accuracy for domain-specific vocabulary.',
          r:[{t:'dbt Docs',u:'https://docs.getdbt.com/'},{t:'Cube.dev Semantic Layer',u:'https://cube.dev/docs'},{t:'LookML Intro',u:'https://cloud.google.com/looker/docs/lookml-intro'}]},
        { d:'Fri', t:'Study natural language data interfaces: analytics copilots, NL query builders. Research tools like Vanna.AI, LangChain SQL Agent, DuckDB.',
          r:[{t:'Vanna.AI Docs',u:'https://vanna.ai/'},{t:'DuckDB Docs',u:'https://duckdb.org/docs/'},{t:'LangChain SQL Agent',u:'https://python.langchain.com/docs/tutorials/sql_qa/'}]},
        { d:'Sat', t:'Build an "Analytics Copilot" end-to-end: NL question → Text-to-SQL → execute on Trino → explain results in NL → visualize as chart.',
          r:[{t:'Plotly Python Docs',u:'https://plotly.com/python/'},{t:'Apache Superset',u:'https://superset.apache.org/docs/'},{t:'Trino Python Client',u:'https://github.com/trinodb/trino-python-client'}]},
        { d:'Sun', t:'Study intelligent alerting for data pipelines: anomaly detection on pipeline metrics, NL alert summaries, root cause analysis agents.',
          r:[{t:'PyOD (anomaly detection)',u:'https://pyod.readthedocs.io/'},{t:'Great Expectations',u:'https://docs.greatexpectations.io/'},{t:'Monte Carlo Data Docs',u:'https://docs.getmontecarlo.com/'}]},
      ]},
    ]
  },
  {
    id: 7, label: 'Phase 7',
    title: 'System Design & End-to-End Projects',
    subtitle: 'Integrate everything. Build things you can demonstrate and discuss deeply in interviews.',
    weeks: [
      { week: 13, days: [
        { d:'Mon', t:'Design: Self-serve analytics agent — full architecture doc covering ingestion, NL query, safety guardrails, eval, observability, and rollback.',
          r:[{t:'System Design Primer (GitHub)',u:'https://github.com/donnemartin/system-design-primer'},{t:'Design Docs at Google',u:'https://www.industrialempathy.com/posts/design-docs-at-google/'},{t:'Architecture Decision Records',u:'https://adr.github.io/'}]},
        { d:'Tue', t:'Design: AI-accelerated pipeline development — agent that understands data contracts and generates Airflow/Spark DAGs from NL requirements.',
          r:[{t:'Data Contracts Guide',u:'https://datacontract.com/'},{t:'Airflow TaskFlow API',u:'https://airflow.apache.org/docs/apache-airflow/stable/tutorial/taskflow.html'},{t:'dbt Docs',u:'https://docs.getdbt.com/'}]},
        { d:'Wed', t:'Design: Intelligent alerting system — streaming pipeline metrics → anomaly detection → LLM root cause analysis → Slack/PagerDuty.',
          r:[{t:'Kafka Streams Docs',u:'https://kafka.apache.org/documentation/streams/'},{t:'Flink CEP (Complex Event Processing)',u:'https://nightlies.apache.org/flink/flink-docs-stable/docs/libs/cep/'},{t:'Prometheus + Grafana',u:'https://prometheus.io/docs/visualization/grafana/'}]},
        { d:'Thu', t:'Design: Multi-model routing layer — classifies task complexity, routes to appropriate model, tracks cost/quality tradeoffs per route.',
          r:[{t:'RouteLLM Paper',u:'https://arxiv.org/abs/2406.18665'},{t:'LiteLLM (universal model router)',u:'https://docs.litellm.ai/'},{t:'Martian (model router)',u:'https://withmartian.com/'}]},
        { d:'Fri', t:'Design: LLM evaluation platform — golden set management, LLM-as-judge, regression CI, drift dashboards, eval versioning.',
          r:[{t:'Promptfoo Docs',u:'https://promptfoo.dev/'},{t:'Langfuse Evals',u:'https://langfuse.com/docs/scores/overview'},{t:'Braintrust',u:'https://www.braintr.us/'}]},
        { d:'Sat', t:'Study privacy-sensitive AI: differential privacy, PII detection/redaction, data masking before LLM calls. Critical for Apple-scale systems.',
          r:[{t:'Google Differential Privacy Library',u:'https://github.com/google/differential-privacy'},{t:'Microsoft Presidio (PII)',u:'https://microsoft.github.io/presidio/'},{t:'Apple: Learning with Privacy at Scale',u:'https://machinelearning.apple.com/research/learning-with-privacy-at-scale'}]},
        { d:'Sun', t:'Study responsible AI: bias evaluation, fairness metrics, model cards, AI incident response. Read ACM FAccT proceedings.',
          r:[{t:'ACM FAccT Proceedings',u:'https://facctconference.org/'},{t:'Model Cards (Google)',u:'https://modelcards.withgoogle.com/'},{t:'AI Incident Database',u:'https://incidentdatabase.ai/'}]},
      ]},
      { week: 14, days: [
        { d:'Mon', t:'Project 1 (Day 1/3): Full Text-to-SQL analytics copilot — NL → Trino → explain results. Set up schema retrieval, few-shot examples, execution engine.',
          r:[{t:'LangChain SQL Agent',u:'https://python.langchain.com/docs/tutorials/sql_qa/'},{t:'Vanna.AI',u:'https://vanna.ai/'},{t:'Trino Python Client',u:'https://github.com/trinodb/trino-python-client'}]},
        { d:'Tue', t:'Project 1 (Day 2/3): Add eval harness (LLM-as-judge on query quality), guardrails (SQL injection prevention), and full distributed tracing.',
          r:[{t:'RAGAS',u:'https://docs.ragas.io/'},{t:'Guardrails AI',u:'https://www.guardrailsai.com/'},{t:'Langfuse Tracing',u:'https://langfuse.com/docs/tracing'}]},
        { d:'Wed', t:'Project 1 (Day 3/3): Polish, write README with architecture diagram, eval results, known limitations, and usage examples.',
          r:[{t:'Mermaid (diagrams as code)',u:'https://mermaid.js.org/'},{t:'Excalidraw (architecture diagrams)',u:'https://excalidraw.com/'},{t:'Make a README',u:'https://www.makeareadme.com/'}]},
        { d:'Thu', t:'Project 2 (Day 1/2): Multi-agent data pipeline generator — takes a data requirement, generates, validates, and tests a pipeline DAG.',
          r:[{t:'LangGraph Multi-Agent Tutorial',u:'https://langchain-ai.github.io/langgraph/tutorials/multi_agent/multi-agent-collaboration/'},{t:'Airflow Python Operator',u:'https://airflow.apache.org/docs/apache-airflow/stable/howto/operator/python.html'}]},
        { d:'Fri', t:'Project 2 (Day 2/2): Add self-healing loop, error recovery, and a cost estimation module. Write architecture doc.',
          r:[{t:'LangGraph Error Handling',u:'https://langchain-ai.github.io/langgraph/how-tos/subgraph-errors/'},{t:'Tenacity (retry library)',u:'https://tenacity.readthedocs.io/'},{t:'LiteLLM Cost Tracking',u:'https://docs.litellm.ai/docs/completion/token_usage'}]},
        { d:'Sat', t:'Project 3: LLM cost optimizer — semantic cache (Redis) + model router + token budget enforcer. Benchmark cost reduction vs baseline.',
          r:[{t:'GPTCache (GitHub)',u:'https://github.com/zilliztech/GPTCache'},{t:'LiteLLM Router',u:'https://docs.litellm.ai/docs/routing'},{t:'Redis Vector Search',u:'https://redis.io/docs/latest/develop/interact/search-and-query/advanced-concepts/vectors/'}]},
        { d:'Sun', t:'Polish all three projects: clean up code, add README, architecture diagram, eval results, and known limitations. Push to GitHub.',
          r:[{t:'GitHub Pages',u:'https://pages.github.com/'},{t:'Excalidraw',u:'https://excalidraw.com/'},{t:'Mermaid Diagrams',u:'https://mermaid.js.org/'}]},
      ]},
    ]
  },
  {
    id: 8, label: 'Phase 8',
    title: 'Interview Prep & Portfolio Polish',
    subtitle: 'Practice articulating tradeoffs, system design, and behavioral stories at senior/staff level.',
    weeks: [
      { week: 15, days: [
        { d:'Mon', t:"Practice ML system design: 'Design a ranking system', 'Design a recommendation engine.' Use Chip Huyen's ML Systems Design book.",
          r:[{t:'Designing ML Systems (Huyen)',u:'https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/'},{t:'ML Interview Prep (GitHub)',u:'https://github.com/alirezadir/Machine-Learning-Interviews'},{t:'ML System Design Course',u:'https://www.educative.io/courses/machine-learning-system-design'}]},
        { d:'Tue', t:"Practice AI system design: 'Design a RAG system at scale', 'Design a multi-agent data engineering assistant for 10k engineers.'",
          r:[{t:'System Design Primer',u:'https://github.com/donnemartin/system-design-primer'},{t:'Grokking System Design',u:'https://www.designgurus.io/course/grokking-the-system-design-interview'},{t:'AI System Design Interviews',u:'https://github.com/alirezadir/Machine-Learning-Interviews'}]},
        { d:'Wed', t:'Practice coding: LeetCode medium/hard on graphs, DP, trees. Focus on Python. Practice writing clean, observable, testable code.',
          r:[{t:'LeetCode',u:'https://leetcode.com/'},{t:'NeetCode (curated list)',u:'https://neetcode.io/'},{t:'Python PEP 8 Style Guide',u:'https://peps.python.org/pep-0008/'}]},
        { d:'Thu', t:'Study distributed systems fundamentals: CAP theorem, consistency models, idempotency — as they apply to AI pipelines and agents.',
          r:[{t:'Designing Data-Intensive Apps (Kleppmann)',u:'https://dataintensive.net/'},{t:'CAP Theorem (IBM)',u:'https://www.ibm.com/topics/cap-theorem'},{t:'Idempotency Patterns (Stripe)',u:'https://stripe.com/blog/idempotency'}]},
        { d:'Fri', t:"Practice explaining AI tradeoffs: 'When to fine-tune vs RAG?', 'How do you evaluate an agent?', 'How do you cut inference cost by 10x?'",
          r:[{t:'RAG vs Fine-tuning Paper',u:'https://arxiv.org/abs/2401.08406'},{t:'LLM Inference Optimization (Lilian Weng)',u:'https://lilianweng.github.io/posts/2023-01-10-inference-optimization/'},{t:'Chip Huyen AI Blog',u:'https://huyenchip.com/blog'}]},
        { d:'Sat', t:"Behavioral prep: STAR stories for 'drove ambiguous project to completion', 'influenced product strategy', 'ran workshop / upleveled a team.'",
          r:[{t:'STAR Method Guide',u:'https://www.themuse.com/advice/star-interview-method'},{t:'Behavioral Interview Prep (levels.fyi)',u:'https://www.levels.fyi/blog/behavioral-interviews.html'},{t:'Amazon Leadership Principles',u:'https://www.amazon.jobs/content/en/our-workplace/leadership-principles'}]},
        { d:'Sun', t:'Mock interview: system design (record yourself or practice with a peer). 5 min clarify, 10 min high-level, 20 min deep dive, 5 min tradeoffs.',
          r:[{t:'interviewing.io',u:'https://interviewing.io/'},{t:'Pramp (free mock interviews)',u:'https://www.pramp.com/'},{t:'Excalidraw (whiteboard)',u:'https://excalidraw.com/'}]},
      ]},
      { week: 16, days: [
        { d:'Mon', t:'Review all 3 capstone projects. Prepare a 5-min demo for each. Anticipate deep-dive questions on every design decision.',
          r:[{t:'Loom (async video demos)',u:'https://www.loom.com/'},{t:'Excalidraw',u:'https://excalidraw.com/'},{t:'GitHub Portfolio Tips',u:'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme'}]},
        { d:'Tue', t:'Review your tech notes and design docs. Turn the best one into a blog post or internal wiki page (practice for the playbook/mentorship expectation).',
          r:[{t:'dev.to (engineering blog)',u:'https://dev.to/'},{t:'Substack',u:'https://substack.com/'},{t:'Google Technical Writing Course',u:'https://developers.google.com/tech-writing'}]},
        { d:'Wed', t:"Study Apple-specific context: iCloud data scale, Apple's privacy-first philosophy, on-device vs cloud AI tradeoffs, differential privacy.",
          r:[{t:'Apple ML Research Blog',u:'https://machinelearning.apple.com/'},{t:'Apple Privacy Site',u:'https://www.apple.com/privacy/'},{t:'CoreML Docs',u:'https://developer.apple.com/documentation/coreml'}]},
        { d:'Thu', t:"Read 5 recent papers from NeurIPS/ICML/ICLR 2024-2025. Practice summarizing: 'What's the idea, does it matter, would I use it?'",
          r:[{t:'Papers With Code',u:'https://paperswithcode.com'},{t:'HuggingFace Daily Papers',u:'https://huggingface.co/papers'},{t:'Arxiv CS.AI',u:'https://arxiv.org/list/cs.AI/recent'}]},
        { d:'Fri', t:'Full mock interview day: coding round + system design round + behavioral round. Debrief, identify gaps, do targeted prep.',
          r:[{t:'interviewing.io',u:'https://interviewing.io/'},{t:'Pramp',u:'https://www.pramp.com/'},{t:'Glassdoor Interview Reviews',u:'https://www.glassdoor.com/'}]},
        { d:'Sat', t:'Rest. Light review of your own notes and design docs. No new learning — consolidate and let it sink in.',
          r:[{t:'Anki (spaced repetition)',u:'https://apps.ankiweb.net/'}]},
        { d:'Sun', t:'Final prep: organize your GitHub profile, update LinkedIn/resume, prepare 5 sharp questions to ask the interviewer about the team and systems.',
          r:[{t:'GitHub Profile README Guide',u:'https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme'},{t:'Reverse Interview Questions',u:'https://github.com/viraptor/reverse-interview'},{t:'LinkedIn AI Jobs',u:'https://www.linkedin.com/jobs/'}]},
      ]},
    ]
  },
];

export const RESOURCES = [
  { phase: 1, title: 'Neural Networks: Zero to Hero', url: 'https://youtube.com/playlist?list=PLAqhIrjkxbuWI23v9cThsA9GvCAUhRvKZ' },
  { phase: 1, title: 'The Illustrated Transformer', url: 'https://jalammar.github.io/illustrated-transformer/' },
  { phase: 1, title: 'Andrej Karpathy — makemore', url: 'https://github.com/karpathy/makemore' },
  { phase: 2, title: 'LangGraph Documentation', url: 'https://langchain-ai.github.io/langgraph/' },
  { phase: 2, title: 'LlamaIndex Documentation', url: 'https://docs.llamaindex.ai' },
  { phase: 2, title: 'FAISS — Getting Started', url: 'https://faiss.ai/index.html' },
  { phase: 3, title: 'LangGraph Multi-Agent Guide', url: 'https://langchain-ai.github.io/langgraph/concepts/multi_agent/' },
  { phase: 3, title: 'Cognitive Architectures for LLMs', url: 'https://arxiv.org/abs/2309.02427' },
  { phase: 4, title: 'RAGAS Framework', url: 'https://docs.ragas.io' },
  { phase: 4, title: 'Langfuse Docs', url: 'https://langfuse.com/docs' },
  { phase: 4, title: 'Made With ML', url: 'https://madewithml.com' },
  { phase: 5, title: 'vLLM Blog', url: 'https://blog.vllm.ai' },
  { phase: 5, title: 'LLM.int8() Paper', url: 'https://arxiv.org/abs/2208.07339' },
  { phase: 5, title: 'Speculative Decoding Paper', url: 'https://arxiv.org/abs/2211.17192' },
  { phase: 6, title: 'Fundamentals of Data Engineering', url: 'https://www.oreilly.com/library/view/fundamentals-of-data/9781098108298/' },
  { phase: 6, title: 'Trino: The Definitive Guide', url: 'https://trino.io/trino-the-definitive-guide.html' },
  { phase: 7, title: 'Designing ML Systems', url: 'https://www.oreilly.com/library/view/designing-machine-learning/9781098107956/' },
  { phase: 7, title: "Chip Huyen's Blog", url: 'https://huyenchip.com' },
  { phase: 8, title: 'Papers With Code', url: 'https://paperswithcode.com' },
  { phase: 8, title: 'System Design Interview Vol. 2', url: 'https://www.amazon.com/System-Design-Interview-Insiders-Guide/dp/1736049119' },
];